name: nas

on:
  push:
    branches:
      - main

# grant GHCR R/W permission to Github Action
permissions:
  contents: read
  packages: write

jobs:
  # GHCR login and build and push
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # login to GHCR
      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # create .env file from Github secrets
      - name: Create .env file
        run: |
          # create .env file for docker compose
          echo "${{ secrets.SERVER_WEBDAV_ENV }}" > webdav/.env

      # build images
      - name: Build images using Docker Compose
        run: |
          docker compose build

      # push to GHCR
      - name: Push images using Docker Compose
        run: |
          docker compose push

  # ssh connection and deploy
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Environment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH Command
        run: |
          ssh -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            echo "ssh connection success"

            # cd project path
            cd ${{ secrets.SERVER_PATH }}

            # renew project code and images
            git pull
            docker compose pull

            # restart compose container
            docker compose up -d --remove-orphans

            # delete old images
            docker image prune -f

            echo "deploy complete"
          EOF